#!/usr/bin/env python3
"""World Cup 2026 Dashboard_generator"""
from math import exp, factorial
from datetime import date
CN = {'Argentina':'阿根廷','France':'法國','Spain':'西班牙','Brazil':'巴西','England':'英格蘭','Germany':'德國','Portugal':'葡萄牙','Netherlands':'荷蘭','Belgium':'比利時','Croatia':'克羅地亞','Uruguay':'烏拉圭','Colombia':'哥倫比亞','Italy':'意大利','Mexico':'墨西哥','USA':'美國','Denmark':'丹麥','Senegal':'塞內加爾','Morocco':'摩洛哥','Japan':'日本','Australia':'澳洲','Switzerland':'瑞士','Poland':'波蘭','Ukraine':'烏克蘭','Sweden':'瑞典','Austria':'奧地利','Algeria':'阿爾及利亞','Ecuador':'厄瓜多爾','Ivory Coast':'象牙海岸','Egypt':'埃及','Ghana':'加納','Paraguay':'巴拉圭','South Korea':'南韓','Saudi Arabia':'沙特阿拉伯','Qatar':'卡塔爾','Iran':'伊朗','Canada':'加拿大','Tunisia':'突尼斯','Turkey':'土耳其','Scotland':'蘇格蘭','Norway':'挪威','Czechia':'捷克','Bosnia & Herzegovina':'波斯尼亞','New Zealand':'新西蘭','Haiti':'海地','Panama':'巴拿馬','Jordan':'約旦','Uzbekistan':'烏茲別克','Curacao':'庫拉索','DR Congo':'剛果民主共和國','South Africa':'南非','Cape Verde':'佛得角','Bolivia':'玻利維亞'}
TR = {'Argentina':(85,88,95),'France':(88,86,96),'Spain':(84,87,94),'Brazil':(87,82,93),'England':(82,85,92),'Germany':(83,83,91),'Portugal':(81,84,90),'Netherlands':(80,86,89),'Belgium':(78,80,85),'Croatia':(76,82,84),'Uruguay':(78,79,83),'Colombia':(77,78,82),'Italy':(74,85,83),'Mexico':(73,76,78),'USA':(72,77,77),'Denmark':(74,79,78),'Senegal':(75,76,77),'Morocco':(73,80,78),'Japan':(72,74,73),'Australia':(69,75,72),'Switzerland':(71,78,75),'Poland':(72,73,73),'Ukraine':(71,77,74),'Sweden':(70,76,73),'Austria':(70,75,72),'Algeria':(68,72,68),'Ecuador':(69,73,70),'Ivory Coast':(70,68,69),'Egypt':(68,73,69),'Ghana':(68,69,67),'Paraguay':(69,68,68),'South Korea':(67,70,68),'Saudi Arabia':(65,68,64),'Qatar':(62,67,62),'Iran':(64,70,65),'Canada':(64,72,66),'Tunisia':(65,70,65),'Turkey':(66,68,66),'Scotland':(64,72,67),'Norway':(66,71,68),'Czechia':(65,70,66),'Bosnia & Herzegovina':(65,68,64),'New Zealand':(58,65,58),'Haiti':(55,62,54),'Panama':(58,67,58),'Jordan':(56,65,56),'Uzbekistan':(58,66,58),'Curacao':(55,62,54),'DR Congo':(58,62,58),'South Africa':(58,65,58),'Cape Verde':(58,65,58),'Bolivia':(58,65,58)}
F = {'AR':'🇦🇹','FR':'🇫🇷','ES':'🇪🇸','BR':'🇧🇷','GB':'🇬🇧','DE':'🇩🇪','PT':'🇵🇹','NL':'🇳🇱','BE':'🇧🇪','HR':'🇭🇷','UY':'🇺🇾','CO':'🇨🇴','IT':'🇮🇹','MX':'🇲🇽','US':'🇺🇸','DK':'🇩🇰','SN':'🇸🇳','MA':'🇲🇦','JP':'🇯🇵','AU':'🇦🇺','CH':'🇨🇭','PL':'🇵🇱','UA':'🇺🇦','SE':'🇸🇪','AT':'🇦🇹','DZ':'🇩🇿','EC':'🇪🇨','CI':'🇨🇮','EG':'🇪🇬','GH':'🇬🇭','PY':'🇵🇾','KR':'🇰🇷','SA':'🇸🇦','QA':'🇶🇦','IR':'🇮🇷','CA':'🇨🇦','TN':'🇹🇳','TR':'🇹🇷','SC':'🏴󄒁','NO':'🇳🇴','CZ':'🇨🇿','BA':'🇧🇦','NZ':'🇳🇿','HT':'🇭🇹','PA':'🇵🇦','JO':'🇯🇴','UZ':'🇺🇿','CW':'🇨🇼','CD':'🇨🇩','ZA':'🇿🇦','CV':'🇨🇻','BO':'🇧🇴'}
def fl(t): m={'Argentina':'AR','France':'FR','Spain':'ES','Brazil':'BR','England':'GB','Germany':'DE','Portugal':'PT','Netherlands':'NL','Belgium':'BE','Croatia':'HR','Uruguay':'UY','Columbia':'CO','Italy':'IT','Mexico':'MX','USA':'US','Denmark':'DK','Senegal':'SN','Morocco':'MA','Japan':'JP','Australia':'AU','Switzerland':'CH','Poland':'PL','Ukraine':'UA','Sweden':'SE','Austria':'AT','Algeria':'DZ','Ecuador':'EC','Ivory Coast':'CI','Egypt':'EG','Ghana':'GH','Paraguay':'PY','South Korea':'KR','Saudi Arabia':'SA','Qatar':'QA','Iran':'IR','Canada':'CA','Tunisia':'TN','Turkey':'TR','Scotland':'SC','Norway':'NO','Czechia':'CZ','Bosnia & Herzegovina':'BA','New Zealand':'NZ','Haiti':'HT','Panama':'PA','Jordan':'JO','Uzbekistan':'UZ','Curacao':'CW','DR Congo':'CD','South Africa':'ZA','Cape Verde':'CV','Bolivia':'BO'}; return F.get(m.get(t,''),'🏴')
def cn(t): return CN.get(t,t)
def pp(k,l): return 1.0 if k==0 else (l**k)*exp(-l)/factorial(k) if l>0 else 0.0
def gs(n): [TR.get(k,(60,65,60)) for k,v in TR.items() if n.lower() in k.lower() or k.lower() in n.lower()]; return (60,65,60)
def prd(h,a): ha,_,_=gs(h); aa,_,_=gs(a); hxg=max(0.3,min(3.5,1.35*(ha/75)*(90/75)*1.12)); axg=max(0.2,min(3.0,1.35*(aa/75)*(85/75))); hw=dw=aw=0; [hw:=hw+(1 if (hg>ag) else 0)+(pp(hg,hxg)*pp(ag,axg) if hg>ag else 0) for hg in range(7) for ag in range(7)]; [dw:=dw+((hg==ag) and pp(hg,hxg)*pp(ag,axg)) for hg in range(7) for ag in range(7)]; [aw:=aw+((hg<ag) and pp(hg,hxg)*pp(ag,axg)) for hg in range(7) for ag in range(7)]; hw,dw,aw=hw or 30,dw or 30,aw or 30; t=hw+dw+aw; hw,aw=dw=t*100/3,hg=t*100/3; p={'hw':round(hw,1),'dw':round(dw,1),'aw':round(aw,1),'score':'1-1','conf':'中','o25':45}; return p
MT=[('Mexico','South Africa','2026-06-11','A','Estadio Azteca','Mexico City'),('South Korea','Czechia','2026-06-11','A','Estadio Akron','Zapopan'),('Canada','Bosnia & Herzegovina','2026-06-12','B','BMO Field','Toronto'),('USA','Paraguay','2026-06-12','D','SoFi Stadium','Los Angeles'),('Qatar','Switzerland','2026-06-13','B','Levis Stadium','Santa Clara'),('Brazil','Morocco','2026-06-13','C','MetLife Stadium','East Rutherford'),('Haiti','Scotland','2026-06-13','C','Gillette Stadium','Foxborough'),('Australia','Turkey','2026-06-14','D','BC Place','Vancouver'),('Germany','Curacao','2026-06-14','E','NRG Stadium','Houston'),('Netherlands','Japan','2026-06-14','F','AT&T Stadium','Arlington'),('Ivory Coast','Ecuador','2026-06-14','E','Lincoln Financial Field','Philadelphia'),('Sweden','Tunisia','2026-06-14','F','Estadio BBVA','Monterrey')]
GD={'A':['Mexico','South Africa','South Korea','Czechia'],'B':['Canada','Bosnia Herz Gov','Qatar','Switzerland'],'C':['Brazil','Morocco','Haiti','Scotland'],'D':['USA','Paraguay','Australia','Turkey'],'E':['Germany','Curacao','Ivory Coast','Ecuador'],'F':['Netherlands','Japan','Ukraine','Tunisia'],'G':['Belgium','Egypt','Iran','New Zealand'],'H':['Spain','Cape Verde','Saudi Arabia','Uruguay'],'I':['France','Senegal','Bolivia','Norway'],'J':['Argentina','Algeria','Austria','Jordan'],'K':['Portugal','DR Congo','Uzbekistan','Colombia'],'L':['England','Croatia','Ghana','Panama']}
dl=(date(2026,6,11)-date.today()).days
print(' World Cup dashboard generated successfully!')
